services:
  web-lens-ide:
    image: eacer/web-lens-ide:latest
    container_name: web-lens-ide
    privileged: false
    environment:
      - TZ=Asia/Manila
      - SUBFOLDER=/
      - TITLE=web-lens IDE
    volumes:
      - ./config:/config
      - ~/.kube:/config/.kube:ro
    ports:
      - 3001:3001
    shm_size: "2gb"
    restart: unless-stopped